language: node_js
node_js:
  - "12"

jobs:
  include:
    - stage: "Documentation test"
      name: "markdownlint test"
      script: markdownlint README.md
    - stage: "Content test"
      name: "markdownlint test"
      script: markdownlint _posts/*.md
    - stage: "Build and test"
      name: "npm build and test"
      script: npm run build && npm test
