safe:        false
port: 4001

source:      .
destination: ./_site

future:      true
lsi:         false
permalink:   /:year/:month/:day/:title

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
