FROM node:12-alpine

WORKDIR /app

ADD web/package.json web/package-lock.json /app/

RUN npm ci

ADD web /app

RUN npm run build-storybook

RUN sed -i 's/<script src="/<script src="\/static\/storybook\//g' static/storybook/iframe.html
